### PR TITLE
Rewrite virtualenv in legacy virtualenv

### PR DESCRIPTION
**Pull request by ionelmc**

### CODE REVIEW

**Comment by ionelmc** [comment]
Hmmm, I think I need to rebase this

**Comment by dstufft** [comment]
Oh yea, probably ;( I rebased without thinking about it. Sorry!

**Comment by ionelmc** [comment]
Almost working, I just need to copy the config dir. Gonna do this tomorrow

**Comment by ionelmc** [comment]
The big change is how the global modules are looked up.

**Pull request closed without merging**
